name: 'Rust MUSL Compile'
description: 'Compile'
author: 'Terence Lee'
inputs:
  command:
    description: 'cargo command'
    required: false
    default: 'build'
  flags:
    description: 'flags passed to cargo build'
    required: false
ouputs:
  release-dir:
    description: 'directory where the binaries are put'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.flags }}
